# --- Dataset ---------------------------------------------
dataset:
  dataset_root: ../data/pix2pix/edges2shoes_32x32_small/train
  image_size: 32

# --- Unet -------------------------------------------------
unet:
  dim: 64                        # base channel dimension
  dim_mults: [1, 2, 4, 8]        # each U-Net stage multiplier
  dropout: 0.1                   # dropout in residual blocks
  channels: 3
  cond_channels: 3
  self_condition: false          # disable self-conditioning when using external conditioning

# --- Diffusion --------------------------------------------
diffusion:
  image_size: 32                 # (H = W)
  timesteps: 1000                # training steps in the noise scheduler
  sampling_timesteps: null

# --- Trainer ----------------------------------------------
trainer:
  train_batch_size: 64
  train_lr: 2e-4
  train_num_steps: 800000        # gradient-steps, not diffusion timesteps
  calculate_fid: true
  calculate_is: true
  save_and_sample_every: 5000
  num_fid_samples: 1000
  results_folder: results/edges2shoes_test
